### PR TITLE
Benchmark for Gravity Waves

### PR DESCRIPTION
**Pull request by jatkinson1000**
Added simple benchmarks for running the 'WaveNet' neural net.

### CODE REVIEW

**Comment by jatkinson1000** [comment]
Running this as a quick test has the following timings:
- Direct: ~0.265 s / iteration
- Forpy: ~0.200 s / iteration

This is roughly consistent with what we saw in the full MiMA runs, so we probably now want to probe this in more detail to understand where we are losing time.

**Comment by TomMelt** [comment]
@jatkinson1000 I decided to gather a larger sample size as I think there is some variance in the runtime.

I have pushed a new commit (1dce3da) to this branch which improves the statistics output and adds the variance.

I then run the code (on my local machine `13th Gen Intel(R) Core(TM) i7-13800H` 14 cores @ 5200 MHz, 32 Gb ram) using the gfortran compiler (`GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`) and the following commands:

```
$ ./benchmarker_cgdrag_torch ../pytorch saved_model.pth 1000 10
$ ./benchmarker_cgdrag_forpy ../pytorch run_emulator_davenet 1000 10
```

Here is my output for 1000 runs of the model compute function:

```
$ tail *out
==> cgdrag_forpy.out <==
 check iteration      995 (     0.970 s)
 check iteration      996 (     1.027 s)
 check iteration      997 (     0.827 s)
 check iteration      998 (     0.876 s)
 check iteration      999 (     1.031 s)
 check iteration     1000 (     0.969 s)
min    time taken (s):     0.5562
max    time taken (s):     3.1618
mean   time taken (s):     0.8627
stddev time taken (s):     0.2038

==> cgdrag_torch.out <==
 check iteration      995 (     0.716 s)
 check iteration      996 (     0.766 s)
 check iteration      997 (     0.713 s)
 check iteration      998 (     0.668 s)
 check iteration      999 (     0.668 s)
 check iteration     1000 (     0.668 s)
min    time taken (s):     0.5571
max    time taken (s):     3.0239
mean   time taken (s):     0.7521
stddev time taken (s):     0.1627
```
This actually implies that the direct coupled method (`cgdrag_torch`) is actually faster.

I also ran this for intel compiler (`ifort (IFORT) 2021.10.0 20230609`) and it was the same:

```
==> cgdrag_forpy.out <==
 check iteration      995 (     0.667 s)
 check iteration      996 (     0.823 s)
 check iteration      997 (     0.722 s)
 check iteration      998 (     0.774 s)
 check iteration      999 (     0.948 s)
 check iteration     1000 (     1.211 s)
min    time taken (s):     0.5524
max    time taken (s):     6.3702
mean   time taken (s):     0.8259
stddev time taken (s):     0.4090

==> cgdrag_torch.out <==
 check iteration      995 (     0.656 s)
 check iteration      996 (     0.866 s)
 check iteration      997 (     0.811 s)
 check iteration      998 (     0.766 s)
 check iteration      999 (     0.711 s)
 check iteration     1000 (     0.714 s)
min    time taken (s):     0.5487
max    time taken (s):     3.1084
mean   time taken (s):     0.7754
stddev time taken (s):     0.1916
```

**Comment by jatkinson1000** [comment]
Just run this on CSD3 as an sbatch job with the following results:

```
 ====== DIRECT COUPLED ======
min    time taken (s):     0.1342
max    time taken (s):     0.2251
mean   time taken (s):     0.1847
stddev time taken (s):     0.0169
```

```
 ====== FORPY ======
min    time taken (s):     0.1189
max    time taken (s):     0.1990
mean   time taken (s):     0.1641
stddev time taken (s):     0.0111
```

so 12% slower direct coupled on HPC for intel build.

**Comment by ElliottKasoar** [comment]
Using [run_benchmarks.sh](https://github.com/Cambridge-ICCS/fortran-pytorch-lib-benchmark/blob/gw_nn_refactor/run_benchmarks.sh), my results on my local machine (WSL Ubuntu, with Intel Core i7-8665U CPU @ 1.90GHz 2.11 GHz, 32.0 GB RAM) seem to be a smaller slowdown:

```
==> cgdrag_forpy_1.out <==
min    time taken (s):     0.1642 [omp]
max    time taken (s):     0.8590 [omp]
mean   time taken (s):     0.2176 [omp]
stddev time taken (s):     0.0512 [omp]
sample size          :        999

==> cgdrag_torch_1.out <==
min    time taken (s):     0.1890 [omp]
max    time taken (s):     0.4668 [omp]
mean   time taken (s):     0.2201 [omp]
stddev time taken (s):     0.0293 [omp]
sample size          :        999


==> cgdrag_forpy_4.out <==
min    time taken (s):     0.1041 [omp]
max    time taken (s):     0.8523 [omp]
mean   time taken (s):     0.1720 [omp]
stddev time taken (s):     0.0655 [omp]
sample size          :        999

==> cgdrag_torch_4.out <==
min    time taken (s):     0.1072 [omp]
max    time taken (s):     0.9748 [omp]
mean   time taken (s):     0.1761 [omp]
stddev time taken (s):     0.0863 [omp]
sample size          :        999


==> cgdrag_forpy_8.out <==
min    time taken (s):     0.1082 [omp]
max    time taken (s):     0.8840 [omp]
mean   time taken (s):     0.1655 [omp]
stddev time taken (s):     0.0668 [omp]
sample size          :        999

==> cgdrag_torch_8.out <==
min    time taken (s):     0.1082 [omp]
max    time taken (s):     0.9879 [omp]
mean   time taken (s):     0.1751 [omp]
stddev time taken (s):     0.0792 [omp]
sample size          :        999
```

The FTorch implementation may have been impacted more by the available resources though, as with `OMP_NUM_THREADS` undefined I previously saw a speedup:

```
==> cgdrag_forpy.out <==
min    time taken (s):     0.0711 [omp]
max    time taken (s):     0.7508 [omp]
mean   time taken (s):     0.1455 [omp]
stddev time taken (s):     0.0442 [omp]
sample size          :        999

==> cgdrag_torch.out <==
min    time taken (s):     0.0765 [omp]
max    time taken (s):     0.2456 [omp]
mean   time taken (s):     0.1314 [omp]
stddev time taken (s):     0.0159 [omp]
sample size          :        999
```

but just after the benchmarking script, I now get a slowdown:

```
==> cgdrag_forpy_new.out <==
min    time taken (s):     0.0710 [omp]
max    time taken (s):     0.3639 [omp]
mean   time taken (s):     0.1414 [omp]
stddev time taken (s):     0.0280 [omp]
sample size          :        999

==> cgdrag_torch_new.out <==
min    time taken (s):     0.1051 [omp]
max    time taken (s):     0.7059 [omp]
mean   time taken (s):     0.1606 [omp]
stddev time taken (s):     0.0567 [omp]
sample size          :        999
```

Once I have access I'll see how it compares on CSD3 with the new timing method.

**Comment by TomMelt** [comment]
Great work. Remember you can return to "before" you set `OMP_NUM_THREADS` by running command:

```
unset OMP_NUM_THREADS
```

**Review by TomMelt — APPROVED** [review]
Resnet example needs tidy up and replacing with Elliotts more realistic version

**Pull request merged**
