### PR TITLE
Melt/update large stride tests

### PR DESCRIPTION
**Pull request by TomMelt**
- I have created a new program for the forpy large stride test and modified the existing torch (directly coupled) program to be consistent.
- They both generate a random N X N matrix/tensor and run the same forward model.
- The output is checked using an assert
- Timings of the two programs are printed to stdout
- Some useful helper functions have been moved into a separate module`benchmarker_utils.f90` so they can be used in both programs.
- I have also updated the CMake to be a bit more general.
- added test results of forpy/torch comparison
- added description of large_stride tests and how to compile/run

### CODE REVIEW

**Review by SimonClifford — APPROVED** [review]
Thanks Tom, this looks really nice.

**Review by jatkinson1000 — CHANGES_REQUESTED** [review]
Thanks so much Tom.

I've checked this out, built, and run.
I would suggest not adding the `saved_model.pth` model as it's a binary, so may well need to be generated by the user for their system using `pt2ts.py` instead.

I also note you build with `Debug` in the instructions.
Since end users will be building with `Release` I tried this, and the two methods become comparable with direct coupling arguably taking a bit longer :/
Furthermore, all runs return `FAILED`

Building with 
```
cmake -DCMAKE_Fortran_COMPILER=ifort -DFTorch_DIR=~/testfplib/lib64/cmake/ -DCMAKE_BUILD_TYPE=Release -DUSETS=1 ..
```
yields
```
(torchvenv) [jwa34@login-q-2 buildTom]$ ./benchmarker_large_stride_forpy ../stridemodel run_emulator_stride 10 512
 ====== FORPY ======
Running model: ../stridemodel/run_emulator_stride 10 times.
 load torchscript model
FAILED :: [check iteration        1 (     2.635 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        2 (     1.691 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        3 (     1.696 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        4 (     1.694 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        5 (     1.688 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        6 (     1.691 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        7 (     1.681 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        8 (     1.690 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        9 (     1.682 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration       10 (     1.682 s)] maximum relative error =  0.1788E-06
 min  time taken (s):    1.681366
 max  time taken (s):    2.635299
 mean time taken (s):    1.782986
(torchvenv) [jwa34@login-q-2 buildTom]$ ./benchmarker_large_stride_torch ../stridemodel saved_model.pth 10 512
 ====== DIRECT COUPLED ======
Running model: ../stridemodel/saved_model.pth 10 times.
FAILED :: [check iteration        1 (     2.622 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        2 (     1.706 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        3 (     1.710 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        4 (     1.708 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        5 (     1.699 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        6 (     1.702 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        7 (     1.697 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        8 (     1.704 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration        9 (     1.695 s)] maximum relative error =  0.1788E-06
FAILED :: [check iteration       10 (     1.699 s)] maximum relative error =  0.1788E-06
 min  time taken (s):    1.694552
 max  time taken (s):    2.621942
 mean time taken (s):    1.794266
```
Can you check this?

**Comment by TomMelt** [comment]
> I've checked this out, built, and run. I would suggest not adding the `saved_model.pth` model as it's a binary, so may well need to be generated by the user for their system using `pt2ts.py` instead.

Yes, I agree. It was already committed to the repo (perhaps a hackathon time constraint). I don't think it should be there either. But I thought since it was I would update it :) We can remove but it will be a pain... we might be better off creating a new repo but I don't mind either way.

> I also note you build with `Debug` in the instructions. Since end users will be building with `Release` I tried this, and the two methods become comparable with direct coupling arguably taking a bit longer :/ Furthermore, all runs return `FAILED`
> 
> Building with
> 
> ```
> cmake -DCMAKE_Fortran_COMPILER=ifort -DFTorch_DIR=~/testfplib/lib64/cmake/ -DCMAKE_BUILD_TYPE=Release -DUSETS=1 ..
> ```
> 
> yields
> 
> ```
> (torchvenv) [jwa34@login-q-2 buildTom]$ ./benchmarker_large_stride_forpy ../stridemodel run_emulator_stride 10 512
>  ====== FORPY ======
> Running model: ../stridemodel/run_emulator_stride 10 times.
>  load torchscript model
> FAILED :: [check iteration        1 (     2.635 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        2 (     1.691 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        3 (     1.696 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        4 (     1.694 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        5 (     1.688 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        6 (     1.691 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        7 (     1.681 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        8 (     1.690 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        9 (     1.682 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration       10 (     1.682 s)] maximum relative error =  0.1788E-06
>  min  time taken (s):    1.681366
>  max  time taken (s):    2.635299
>  mean time taken (s):    1.782986
> (torchvenv) [jwa34@login-q-2 buildTom]$ ./benchmarker_large_stride_torch ../stridemodel saved_model.pth 10 512
>  ====== DIRECT COUPLED ======
> Running model: ../stridemodel/saved_model.pth 10 times.
> FAILED :: [check iteration        1 (     2.622 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        2 (     1.706 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        3 (     1.710 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        4 (     1.708 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        5 (     1.699 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        6 (     1.702 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        7 (     1.697 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        8 (     1.704 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration        9 (     1.695 s)] maximum relative error =  0.1788E-06
> FAILED :: [check iteration       10 (     1.699 s)] maximum relative error =  0.1788E-06
>  min  time taken (s):    1.694552
>  max  time taken (s):    2.621942
>  mean time taken (s):    1.794266
> ```
> 
> Can you check this?

Here are my thoughts:

1. I don't think it's an issue. I was perhaps a bit too strict when setting the default relative tolerance in `assert_real_2d` to `rtol = 1e-10`. Considering we are using floats and not doubles it would perhaps be better to change this to `1e-05` or something.
2. interestingly, `gfortran` :angel: doesn't suffer from this float error and so even in Release mode it produces near identical results.
3. you can check by adding an additional flag to the `CMakeLists.txt` that the error changes whether or not the fortran reals are double (`-r8`) or single (`-r4`). Obviously, we then send it to python/c++ anyway as floats so you will still get a rounding error.
```cmake
elseif (CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
    set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fpp -warn all -r8")
endif()
```

Let me know what you think of this.

**Comment by TomMelt** [comment]
@jatkinson1000 I have just pushed a commit to increase the relative error tolerance so that the tests will pass. You can try them again now and it should run. 

Although there is still the possibility I am missing something

**Review by jatkinson1000 — APPROVED** [review]
All makes sense.
We can worry about compiler flags at a later date, and timing is still under investigation.

LGTM, so merging to continue work.

**Pull request merged**
